version: '3.8'
services:
  apicone:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - ollama
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: apicone
      POSTGRES_USER: apicone
      POSTGRES_PASSWORD: apiconepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
volumes:
  pgdata:
  ollama_data:
